verbose: false
demo: true
start_x: 0.0
start_y: -0.20
start_z: 0.0
dbscan_eps: 0.5
dbscan_min_samples: 4
min_quality: 0.5
integration_enabled: true
damping: true
omega_factor: 0.2
stop_time: 2.0
integration_assisted_clustering: true
show_time_keeping: false
